import { Config, CrossLayerProps, FeaturesContext } from '@node-in-layers/core'
import { Namespace } from '../types.js'
import { PackageFeaturesLayer, PackageServicesLayer } from '../package/types.js'
import { TemplatingServicesLayer, PackageType } from '../templating/types.js'
import { SdkFeaturesLayer } from '../sdk/types.js'
import { BackendFeaturesLayer } from '../backend/types.js'
import { FrontendFeaturesLayer } from '../frontend/types.js'
import { createValidSystemName } from './libs.js'
import { SystemServicesLayer } from './types.js'
import path from 'node:path'
import { WorkspaceServicesLayer } from '../workspace/types.js'

export const create = (
  context: FeaturesContext<
    Config,
    SystemServicesLayer &
      TemplatingServicesLayer &
      PackageServicesLayer &
      WorkspaceServicesLayer,
    PackageFeaturesLayer &
      SdkFeaturesLayer &
      BackendFeaturesLayer &
      FrontendFeaturesLayer
  >
) => {
  const createSystem = async (
    props: {
      systemName: string
      systemLanguage: PackageType
      sdkName: string
      sdkTransport: 'mcp' | 'rest'
      backendName: string
      backendType: 'mcp' | 'rest'
      frontendName?: string
      noFrontend?: boolean
    },
    crossLayerProps?: CrossLayerProps
  ) => {
    const log = context.log.getInnerLogger('createSystem', crossLayerProps)
    const { systemLanguage } = props
    const systemName = createValidSystemName(props.systemName)

    if (systemLanguage !== PackageType.typescript) {
      throw new Error('Only TypeScript systems are supported at this time.')
    }

    // Create system directory and write marker
    const rootPath = path.join(context.constants.workingDirectory, systemName)
    await context.services[Namespace.workspace].ensureDirectory(
      {
        inPath: rootPath,
      },
      crossLayerProps
    )
    await context.services[Namespace.workspace].writeSystemMarker(
      {
        inPath: rootPath,
        systemJson: {
          name: systemName,
          description:
            'This is a Node in Layers system, generated by the Node in Layers Toolkit.',
          sdkName: '.',
          backends: [props.backendName],
          frontends: props.noFrontend ? [] : [props.frontendName || 'frontend'],
        },
      },
      crossLayerProps
    )

    // Create SDK and API under system directory
    await context.features[Namespace.sdk].createSdk(
      {
        sdkName: props.sdkName,
        transport: props.sdkTransport,
        packageType: systemLanguage,
        rootDirName: systemName,
      },
      crossLayerProps
    )

    await context.features[Namespace.backend].createBackend(
      {
        backendName: props.backendName,
        type: props.backendType || 'mcp',
        sdkName: props.sdkName,
        packageType: systemLanguage,
        rootDirName: systemName,
      },
      crossLayerProps
    )

    // Link SDK into API (from system dir)
    context.services[Namespace.system].linkSdkInPackage(
      { systemName, packageName: props.backendName, sdkName: props.sdkName },
      crossLayerProps
    )

    // Optionally create frontend (React) and link SDK
    if (!props.noFrontend) {
      const frontendName = props.frontendName || 'frontend'
      await context.features[Namespace.frontend].createFrontend(
        {
          frontendName,
          framework: 'react',
          sdkName: props.sdkName,
          rootDirName: systemName,
        },
        crossLayerProps
      )
      context.services[Namespace.system].linkSdkInPackage(
        { systemName, packageName: frontendName, sdkName: props.sdkName },
        crossLayerProps
      )
    }

    log.info('System scaffolding complete')
    return
  }

  return {
    createSystem,
  }
}
