import path from 'node:path'
import { FeaturesContext, Config, CrossLayerProps } from '@node-in-layers/core'
import { Namespace } from '../types.js'
import { TemplatingServicesLayer } from '../templating/types.js'
import { applyTemplates, createValidName } from '../templating/libs.js'
import { BackendServicesLayer } from './types.js'
import { WorkspaceServicesLayer } from '../workspace/types.js'
import { PackageServicesLayer } from '../package/types.js'

export const create = (
  context: FeaturesContext<
    Config,
    BackendServicesLayer &
      TemplatingServicesLayer &
      WorkspaceServicesLayer &
      PackageServicesLayer
  >
) => {
  const createBackend = async (
    props: {
      backendName?: string
      type?: 'mcp' | 'rest'
      sdkName?: string
      rootDirName?: string
      packageType?: any
      new?: boolean
    },
    crossLayerProps?: CrossLayerProps
  ) => {
    const log = context.log.getInnerLogger('createBackend', crossLayerProps)

    if (!props || !props.backendName) {
      throw new Error('backendName is required')
    }
    if (!props.type) {
      throw new Error('type is required (mcp|rest)')
    }
    if (!props.sdkName) {
      throw new Error('sdkName is required')
    }

    const backendName = createValidName(props.backendName || 'backend')
    const isNewSystem = Boolean(props.new)

    const basePath = isNewSystem
      ? path.join(context.constants.workingDirectory, backendName)
      : props.rootDirName
        ? path.join(context.constants.workingDirectory, props.rootDirName)
        : context.constants.workingDirectory

    if (isNewSystem) {
      log.info('Creating new system root')
      await context.services[Namespace.workspace].ensureDirectory({
        inPath: basePath,
      })
      await context.services[Namespace.workspace].writeSystemMarker(
        {
          inPath: basePath,
          systemJson: {
            name: backendName,
            description:
              'This is a Node in Layers system, generated by the Node in Layers Toolkit.',
            sdkName: '.',
            backends: ['.'],
            frontends: [],
          },
        },
        crossLayerProps
      )
    } else {
      const inRoot = await context.services[Namespace.backend].isSystemRoot(
        { inPath: basePath },
        crossLayerProps
      )
      if (!inRoot) {
        throw new Error(
          `Must be executed in a Node In Layers system root (directory containing nil.system.json).`
        )
      }
    }

    const systemNameRaw = isNewSystem
      ? backendName
      : await context.services[Namespace.workspace].getSystemName(
          { inPath: basePath },
          crossLayerProps
        )
    const systemName = systemNameRaw.startsWith('@')
      ? systemNameRaw
      : `@${systemNameRaw}`

    const fullBackendPackageName = `${systemName}/${backendName}`
    const sdkNameRaw = props.sdkName || 'sdk'
    const sdkName = sdkNameRaw === '.' ? '.' : createValidName(sdkNameRaw)
    const fullSdkPackageName = sdkName === '.' ? '' : `${systemName}/${sdkName}`

    const fullPath = isNewSystem
      ? backendName
      : props.rootDirName
        ? path.join(props.rootDirName, backendName)
        : backendName

    if (!isNewSystem) {
      const alreadyExists = context.services[
        Namespace.backend
      ].doesBackendAlreadyExist(
        {
          backendName,
          rootDirName: props.rootDirName,
        },
        crossLayerProps
      )
      if (alreadyExists) {
        throw new Error(`Backend ${backendName} already exists.`)
      }
    }
    const packageType = await context.services[
      Namespace.backend
    ].getPackageType({ packageType: 'typescript' }, crossLayerProps)
    const backendType = props.type || 'mcp'
    if (backendType === 'rest') {
      throw new Error(
        'REST API scaffolding is not implemented yet. Please use --type mcp (default).'
      )
    }
    const templates = await context.services[
      Namespace.templating
    ].readTemplates(
      { name: 'backend', packageType, nested: backendType },
      crossLayerProps
    )
    const versions = {
      nodeInLayersCoreVersion: await context.services[
        Namespace.templating
      ].getDependencyVersion({ key: '@node-in-layers/core' }, crossLayerProps),
      nodeInLayersDataVersion: await context.services[
        Namespace.templating
      ].getDependencyVersion({ key: '@node-in-layers/data' }, crossLayerProps),
      nodeInLayersMcpServerVersion: await context.services[
        Namespace.templating
      ].getDependencyVersion(
        { key: '@node-in-layers/mcp-server' },
        crossLayerProps
      ),
      nodeInLayersRestServerVersion: await context.services[
        Namespace.templating
      ].getDependencyVersion(
        { key: '@node-in-layers/rest-api' },
        crossLayerProps
      ),
      functionalModelsVersion: await context.services[
        Namespace.templating
      ].getDependencyVersion({ key: 'functional-models' }, crossLayerProps),
      functionalModelsOrmMcpVersion: await context.services[
        Namespace.templating
      ].getDependencyVersion(
        { key: 'functional-models-orm-mcp' },
        crossLayerProps
      ),
    }
    const data = {
      versions,
      backendName,
      systemName,
      fullBackendPackageName,
      sdkName,
      fullSdkPackageName,
      backendType,
      includeSdkDependency: sdkName !== '.',
    }
    const appliedTemplates = applyTemplates(templates, data)
    log.info('Writing templates')
    context.services[Namespace.templating].writeTemplates(
      {
        packageName: backendName,
        templates: appliedTemplates,
        options: isNewSystem
          ? { baseDirName: backendName, ignoreNameInDir: true }
          : { baseDirName: props.rootDirName },
      },
      crossLayerProps
    )

    if (!isNewSystem) {
      log.info('Adding Backend Name')
      await context.services[Namespace.workspace].addBackendName(
        { inPath: basePath, backendName },
        crossLayerProps
      )
    }

    log.info('Running NPM Install')
    context.services[Namespace.package].executeBashCommand(
      {
        packageName: fullPath,
        command: 'npm install',
      },
      crossLayerProps
    )
    log.info('Running NPM Build')
    context.services[Namespace.package].executeBashCommand(
      {
        packageName: fullPath,
        command: 'npm run build',
      },
      crossLayerProps
    )
    log.info('Running NPM Prettier')
    context.services[Namespace.package].executeBashCommand(
      {
        packageName: fullPath,
        command: 'npm run prettier',
      },
      crossLayerProps
    )
    log.info('Running NPM Eslint')
    context.services[Namespace.package].executeBashCommand(
      {
        packageName: fullPath,
        command: 'npm run eslint',
      },
      crossLayerProps
    )
    log.info('Operation complete')
  }

  return { createBackend }
}
