import path from 'node:path'
import { FeaturesContext, Config, CrossLayerProps } from '@node-in-layers/core'
import { Namespace } from '../types.js'
import { PackageServicesLayer } from '../package/types.js'
import { TemplatingServicesLayer } from '../templating/types.js'
import { applyTemplates, createValidName } from '../templating/libs.js'
import {
  buildTemplateVersions,
  COMMON_DEV,
  COMMON_RUNTIME,
  NIL_BACKEND,
} from '../templating/dependencyVersions.js'
import { WorkspaceServicesLayer } from '../workspace/types.js'
import { BackendServicesLayer } from './types.js'

type BackendCreateContext = FeaturesContext<
  Config,
  BackendServicesLayer &
    TemplatingServicesLayer &
    WorkspaceServicesLayer &
    PackageServicesLayer
>

const BACKEND_RUNTIME = COMMON_RUNTIME.filter(pkg =>
  [
    'functional-models',
    'functional-models-orm-mcp',
    'argparse',
    'es-main',
    'express',
    'zod',
  ].includes(pkg)
)

const runBackendPackageLifecycle = (
  context: BackendCreateContext,
  fullPath: string,
  log: { info: (message: string) => void },
  crossLayerProps?: CrossLayerProps
) => {
  const pkg = Namespace.package
  const run = (command: string) =>
    context.services[pkg].executeBashCommand(
      { packageName: fullPath, command },
      crossLayerProps
    )
  log.info('Running NPM Install')
  run('npm install')
  log.info('Running NPM Build')
  run('npm run build')
  log.info('Running NPM Prettier')
  run('npm run prettier')
  log.info('Running NPM Eslint')
  run('npm run eslint')
}

const setupNewSystemRoot = async (
  context: BackendCreateContext,
  basePath: string,
  backendName: string,
  log: { info: (message: string) => void },
  crossLayerProps?: CrossLayerProps
) => {
  log.info('Creating new system root')
  await context.services[Namespace.workspace].ensureDirectory({
    inPath: basePath,
  })
  await context.services[Namespace.workspace].writeSystemMarker(
    {
      inPath: basePath,
      systemJson: {
        name: backendName,
        description:
          'This is a Node in Layers system, generated by the Node in Layers Toolkit.',
        sdkName: '.',
        backends: ['.'],
        frontends: [],
      },
    },
    crossLayerProps
  )
}

const assertExistingSystemRoot = async (
  context: BackendCreateContext,
  basePath: string,
  crossLayerProps?: CrossLayerProps
) => {
  const inRoot = await context.services[Namespace.backend].isSystemRoot(
    { inPath: basePath },
    crossLayerProps
  )
  if (!inRoot) {
    throw new Error(
      `Must be executed in a Node In Layers system root (directory containing nil.system.json).`
    )
  }
}

const assertBackendDoesNotExist = (
  context: BackendCreateContext,
  backendName: string,
  rootDirName: string | undefined,
  crossLayerProps?: CrossLayerProps
) => {
  const alreadyExists = context.services[
    Namespace.backend
  ].doesBackendAlreadyExist(
    {
      backendName,
      rootDirName,
    },
    crossLayerProps
  )
  if (alreadyExists) {
    throw new Error(`Backend ${backendName} already exists.`)
  }
}

const assertMcpBackendType = (backendType: string) => {
  if (backendType === 'rest') {
    throw new Error(
      'REST API scaffolding is not implemented yet. Please use --type mcp (default).'
    )
  }
}

const addBackendToSystemMarkerIfNeeded = async (
  context: BackendCreateContext,
  isNewSystem: boolean,
  basePath: string,
  backendName: string,
  log: { info: (message: string) => void },
  crossLayerProps?: CrossLayerProps
) => {
  if (isNewSystem) {
    return
  }
  log.info('Adding Backend Name')
  await context.services[Namespace.workspace].addBackendName(
    { inPath: basePath, backendName },
    crossLayerProps
  )
}

export const create = (context: BackendCreateContext) => {
  const createBackend = async (
    props: {
      backendName?: string
      type?: 'mcp' | 'rest'
      sdkName?: string
      rootDirName?: string
      packageType?: any
      new?: boolean
    },
    crossLayerProps?: CrossLayerProps
  ) => {
    const log = context.log.getInnerLogger('createBackend', crossLayerProps)

    if (!props || !props.backendName) {
      throw new Error('backendName is required')
    }
    if (!props.type) {
      throw new Error('type is required (mcp|rest)')
    }
    const backendName = createValidName(props.backendName || 'backend')
    const isNewSystem = Boolean(props.new)

    const basePath = isNewSystem
      ? path.join(context.constants.workingDirectory, backendName)
      : props.rootDirName
        ? path.join(context.constants.workingDirectory, props.rootDirName)
        : context.constants.workingDirectory

    if (isNewSystem) {
      await setupNewSystemRoot(
        context,
        basePath,
        backendName,
        log,
        crossLayerProps
      )
    } else {
      await assertExistingSystemRoot(context, basePath, crossLayerProps)
    }

    const systemNameRaw = isNewSystem
      ? backendName
      : await context.services[Namespace.workspace].getSystemName(
          { inPath: basePath },
          crossLayerProps
        )
    const systemName = systemNameRaw.startsWith('@')
      ? systemNameRaw
      : `@${systemNameRaw}`

    const fullBackendPackageName = `${systemName}/${backendName}`
    const sdkNameRaw = props.sdkName ?? (isNewSystem ? '.' : 'sdk')
    const sdkName = sdkNameRaw === '.' ? '.' : createValidName(sdkNameRaw)
    const fullSdkPackageName = sdkName === '.' ? '' : `${systemName}/${sdkName}`

    const fullPath = isNewSystem
      ? backendName
      : props.rootDirName
        ? path.join(props.rootDirName, backendName)
        : backendName

    if (!isNewSystem) {
      assertBackendDoesNotExist(
        context,
        backendName,
        props.rootDirName,
        crossLayerProps
      )
    }
    const packageType = await context.services[
      Namespace.backend
    ].getPackageType({ packageType: 'typescript' }, crossLayerProps)
    const backendType = props.type || 'mcp'
    assertMcpBackendType(backendType)
    const templates = await context.services[
      Namespace.templating
    ].readTemplates(
      { name: 'backend', packageType, nested: backendType },
      crossLayerProps
    )
    const versions = await buildTemplateVersions(
      context,
      { include: [...NIL_BACKEND, ...BACKEND_RUNTIME, ...COMMON_DEV] },
      crossLayerProps
    )
    const data = {
      ...versions,
      backendName,
      systemName,
      fullBackendPackageName,
      sdkName,
      fullSdkPackageName,
      backendType,
      includeSdkDependency: sdkName !== '.',
    }
    const appliedTemplates = applyTemplates(templates, data)
    log.info('Writing templates')
    context.services[Namespace.templating].writeTemplates(
      {
        packageName: backendName,
        templates: appliedTemplates,
        options: isNewSystem
          ? { baseDirName: backendName, ignoreNameInDir: true }
          : { baseDirName: props.rootDirName },
      },
      crossLayerProps
    )

    await addBackendToSystemMarkerIfNeeded(
      context,
      isNewSystem,
      basePath,
      backendName,
      log,
      crossLayerProps
    )

    runBackendPackageLifecycle(context, fullPath, log, crossLayerProps)
    log.info('Operation complete')
  }

  return { createBackend }
}
